;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hydra-mark/er/mark-symbol-and-exit
        hydra-transpose/transpose-sexps-and-exit
        hydra-transpose/transpose-words-and-exit
        paredit-backward-down
        paredit-backward-up
        paredit-close-square
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-up
        paredit-raise-sexp
        transpose-sexps
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-transpose/body
        hydra-mark/body
        multiple-cursors-hydra/mc/edit-beginnings-of-lines-and-exit
        multiple-cursors-hydra/mc/edit-ends-of-lines-and-exit
        multiple-cursors-hydra/mc/edit-lines-and-exit
        multiple-cursors-hydra/mc/mark-all-dwim-and-exit
        multiple-cursors-hydra/mc/mark-all-symbols-like-this-and-exit
        multiple-cursors-hydra/mc/mark-all-symbols-like-this-in-defun-and-exit
        multiple-cursors-hydra/mc/mark-all-words-like-this-and-exit
        multiple-cursors-hydra/mc/mark-all-words-like-this-in-defun-and-exit
        smex
        ))
