;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        company-indent-or-complete-common
        hydra-mark/er/mark-symbol-and-exit
        hydra-transpose/transpose-sexps-and-exit
        hydra-transpose/transpose-words-and-exit
        paredit-backward-down
        paredit-backward-up
        paredit-close-square
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-up
        paredit-raise-sexp
        transpose-sexps
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-clj-refactor-a/body
        hydra-clj-refactor-c/body
        hydra-clj-refactor-d/body
        hydra-clj-refactor-e/body
        hydra-clj-refactor-e/cljr-extract-constant-and-exit
        hydra-clj-refactor-e/cljr-extract-function-and-exit
        hydra-clj-refactor-f/body
        hydra-clj-refactor-h/body
        hydra-clj-refactor-i/body
        hydra-clj-refactor-i/cljr-introduce-let-and-exit
        hydra-clj-refactor-m/body
        hydra-clj-refactor-p/body
        hydra-clj-refactor-r/body
        hydra-clj-refactor-s/body
        hydra-clj-refactor-t/body
        hydra-clj-refactor-u/body
        hydra-mark/body
        hydra-transpose/body
        multiple-cursors-hydra/mc/edit-beginnings-of-lines-and-exit
        multiple-cursors-hydra/mc/edit-ends-of-lines-and-exit
        multiple-cursors-hydra/mc/edit-lines-and-exit
        multiple-cursors-hydra/mc/mark-all-dwim-and-exit
        multiple-cursors-hydra/mc/mark-all-symbols-like-this-and-exit
        multiple-cursors-hydra/mc/mark-all-symbols-like-this-in-defun-and-exit
        multiple-cursors-hydra/mc/mark-all-words-like-this-and-exit
        multiple-cursors-hydra/mc/mark-all-words-like-this-in-defun-and-exit
        smex
        ))
